import type { AIProvider, ChatMessage, ChatOptions, ToolCall } from '../../infra/provider.ts';
import type { SkillDefinition, ToolCallRecord } from './types.ts';
import type { SkillCallRecord } from '../state.ts';
import type { StructuredOutputProfile } from '../structured-output/profile.ts';
import { Log } from '../../../../shared/services/logger.ts';
import { zodToJsonSchema, makeSchemaOpenAICompatible } from './json-schema.ts';
import { tryExtractJson } from './json-extract.ts';
import { compactReActConversation } from './react-context.ts';
import { tryExtractFromDeclareTools } from './declare-extract.ts';

// Re-export the schema/JSON/declare utilities so existing importers (structured-
// output profiles, tests) keep resolving them from `utils.ts`.
export { zodToJsonSchema, makeSchemaOpenAICompatible, compactReActConversation, tryExtractFromDeclareTools };

/**
 * Project raw ReAct tool-call records into the state's `skillCalls` channel.
 * Every agent node persists the same shape, so this lives in one place.
 */
export function toSkillCallRecords(
  agentName: string,
  toolCallRecords: ToolCallRecord[] | undefined,
): SkillCallRecord[] {
  return (toolCallRecords ?? []).map((tc) => ({
    agent: agentName,
    skillName: tc.name,
    input: tc.input,
    output: tc.output,
    latencyMs: tc.latencyMs,
    timestamp: Date.now(),
  }));
}

/**
 * Convert SkillDefinition[] to ChatOptions.tools format
 */
export function skillsToChatTools(skills: SkillDefinition[]): ChatOptions['tools'] {
  if (!skills || skills.length === 0) return undefined;
  return skills.map((s) => ({
    name: s.name,
    description: s.description,
    parameters: zodToJsonSchema(s.schema) as any,
  }));
}

/**
 * Strip fields the builder always overrides (temperature/responseFormat/tools/
 * toolChoice) from `extra`, so per-call overrides never resurrect a value the
 * Phase 1 / Phase 2 options explicitly control.
 */
function stripOptionOverrides(extra?: Partial<ChatOptions>): Partial<ChatOptions> {
  const { temperature: _temperature, responseFormat: _responseFormat, tools: _tools, toolChoice: _toolChoice, ...rest } = extra ?? {};
  return rest;
}

/**
 * Build ChatOptions: Phase 1 thinking + ReAct stage
 * Only expose business tools; final structured output is generated by the subsequent extraction stage.
 */
export function buildThinkingChatOptions(
  skills: SkillDefinition[],
  extra?: Partial<ChatOptions>,
): ChatOptions {
  const allowedExtra = stripOptionOverrides(extra);
  
  // Build tool list: only business skills. Final JSON is generated by the subsequent extraction stage to avoid the thinking stage depending on the model proactively submitting a structured payload.
  const businessTools = skillsToChatTools(skills);
  
  return {
    temperature: 0.5,
    tools: businessTools,
    toolChoice: businessTools && businessTools.length > 0 ? 'auto' : undefined,
    ...allowedExtra,
  };
}

/**
 * Build ChatOptions: Phase 2 extraction stage, using json_schema response_format
 */
export function buildExtractionChatOptions(
  outputProfile: StructuredOutputProfile<unknown>,
  extra?: Partial<ChatOptions>,
): ChatOptions {
  const allowedExtra = stripOptionOverrides(extra);
  return {
    jsonSchema: outputProfile.toolSchema,
    temperature: 0,
    ...allowedExtra,
  };
}

/**
 * Build the Phase 2 extraction prompt, including schema constraints
 */
export function buildExtractionPrompt(outputProfile: StructuredOutputProfile<unknown>): string {
  const schema = outputProfile.toolSchema;
  const hints = outputProfile.extractionHints;
  const hintsSection = hints ? `\n\nAdditional constraints (JSON Schema cannot express these — follow strictly):\n${hints}` : '';
  return `Based on the analysis above, output a single JSON object matching this schema. Do NOT include any text before or after the JSON.

Schema:
${JSON.stringify(schema, null, 2)}${hintsSection}`;
}

// ============================================================
// ReAct Loop
// ============================================================

const MAX_REACT_ROUNDS = 30;

// E3: Truncate large tool results to avoid context bloat
const MAX_TOOL_RESULT_CHARS = 6000;
function truncateToolResult(content: string): string {
  if (!content || typeof content !== 'string') return '';
  if (content.length <= MAX_TOOL_RESULT_CHARS) return content;
  return content.slice(0, MAX_TOOL_RESULT_CHARS) + `\n...(truncated, ${content.length} chars total)`;
}

export class ToolStateProjectionError extends Error {
  constructor() {
    super('Tool state projection failed');
    this.name = 'ToolStateProjectionError';
  }
}

function serializeToolResult(result: unknown): { content: string; stateOutput: unknown } {
  if (typeof result === 'string') return { content: result, stateOutput: result };
  try {
    const content = JSON.stringify(result, null, 2);
    return typeof content === 'string'
      ? { content, stateOutput: JSON.parse(content) }
      : { content: 'null', stateOutput: null };
  } catch {
    return { content: 'null', stateOutput: null };
  }
}

function projectToolCallForState(
  skill: SkillDefinition,
  input: unknown,
  result: unknown,
  stateOutput: unknown,
  meta: { latencyMs: number; resultSize: number },
): { input: unknown; output: unknown } {
  if (!skill.summarizeForState) return { input, output: stateOutput };

  let projection: unknown;
  try {
    projection = skill.summarizeForState(input, result, meta);
  } catch {
    throw new ToolStateProjectionError();
  }
  let normalizedProjection: unknown;
  try {
    const serialized = JSON.stringify(projection);
    if (serialized === undefined) throw new ToolStateProjectionError();
    normalizedProjection = JSON.parse(serialized);
  } catch {
    throw new ToolStateProjectionError();
  }
  if (!normalizedProjection
    || typeof normalizedProjection !== 'object'
    || Array.isArray(normalizedProjection)
    || !Object.hasOwn(normalizedProjection, 'input')
    || !Object.hasOwn(normalizedProjection, 'output')) {
    throw new ToolStateProjectionError();
  }
  return normalizedProjection as { input: unknown; output: unknown };
}

function extractedValueSummary(value: unknown): { type: string; keys: string[]; draftTestCases: string } {
  const keys = value && typeof value === 'object' ? Object.keys(value as Record<string, unknown>) : [];
  const draftTestCases = (value as any)?.draftTestCases ? typeof (value as any).draftTestCases : 'missing';
  return { type: typeof value, keys, draftTestCases };
}

/**
 * Consume an extraction-stage stream (Phase 1.5 nudge / Phase 2 retry loop),
 * accumulating content and token usage.
 */
async function consumeExtractionStream(
  provider: AIProvider,
  messages: ChatMessage[],
  options: ChatOptions,
  observer: { onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void },
  name: string,
  usage: { input: number; output: number; reasoning: number; cached: number },
): Promise<string> {
  let content = '';
  for await (const chunk of provider.streamChat(messages, options)) {
    if (chunk.type === 'content' && chunk.content) {
      content += chunk.content;
      observer?.onThinking?.(name, chunk.content, 'content', 'extraction');
    }
    if (chunk.type === 'done' && chunk.usage) {
      usage.input += (chunk.usage.promptTokens || 0);
      usage.output += (chunk.usage.completionTokens || 0);
      usage.reasoning += (chunk.usage.reasoningTokens || 0);
      usage.cached += (chunk.usage.cachedPromptTokens || 0);
    }
  }
  return content;
}

interface ReActResult {
  contentText: string;
  thinkingText: string;
  toolCallRecords: ToolCallRecord[];
  usage: { input: number; output: number; reasoning: number; cached: number };
  conversationMessages: ChatMessage[];
}

/**
 * Execute the ReAct loop: LLM thinks → call tool → observe result → continue thinking
 * At most MAX_REACT_ROUNDS rounds; exit when there are no tool_calls
 */
async function runAgentReActLoop(
  provider: AIProvider,
  messages: ChatMessage[],
  skills: SkillDefinition[],
  outputProfile: StructuredOutputProfile<unknown>,
  observer: {
    onStep?: (name: string, idx: number, step: string) => void;
    onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void;
    onToolCall?: (name: string, toolCall: ToolCallRecord) => void;
  },
  agentName: string,
  extra: Partial<ChatOptions> | undefined,
): Promise<ReActResult> {
  const skillMap = new Map(skills.map((s) => [s.name, s]));
  const log = Log.for(`react:${agentName}`);
  log.info(`ReAct loop start ── ${skills.length} skills: ${skills.map(s => s.name).join(', ')}`);
  const allMessages: ChatMessage[] = [...messages];
  let contentText = '';
  let thinkingText = '';
  const toolCallRecords: ReActResult['toolCallRecords'] = [];
  let capturedUsage = {
    input: 0,
    output: 0,
    reasoning: 0,
    cached: 0,
  };
  let totalRounds = 0;

  observer?.onStep?.(agentName, 0, 'Phase 1: Analysis started');

  for (let round = 0; round < MAX_REACT_ROUNDS; round++) {
    totalRounds = round + 1;
    // Stream call to LLM (with tools)
    let roundContent = '';
    let roundThinking = '';
    const pendingToolCalls: ToolCall[] = [];

    // 上下文窗口压缩：只发送 base + 最近几轮完整消息，更早轮次的工具结果摘要化，
    // 防止每轮重发全部历史导致 O(n²) token 膨胀（实测 Designer 单 run input 260k tokens）。
    const sendMessages = compactReActConversation(allMessages, messages.length);

    for await (const chunk of provider.streamChat(sendMessages, buildThinkingChatOptions(skills, extra))) {
      if (chunk.type === 'reasoning' && chunk.content) {
        roundThinking += chunk.content;
        observer?.onThinking?.(agentName, chunk.content, 'reasoning', 'react');
      }
      if (chunk.type === 'content' && chunk.content) {
        roundContent += chunk.content;
        observer?.onThinking?.(agentName, chunk.content, 'content', 'react');
      }
      if (chunk.type === 'tool_call_start' && chunk.toolCall) {
        pendingToolCalls.push(chunk.toolCall);
      }
      if (chunk.type === 'tool_call_delta' && chunk.toolCall) {
        const existing = pendingToolCalls.find((tc) => tc.id === chunk.toolCall!.id);
        if (existing) {
          existing.args = chunk.toolCall.args; // The last delta contains the complete args
        } else {
          pendingToolCalls.push(chunk.toolCall);
        }
      }
      if (chunk.type === 'tool_call_end' && chunk.toolCall) {
        const existing = pendingToolCalls.find((tc) => tc.id === chunk.toolCall!.id);
        if (existing) {
          existing.args = chunk.toolCall.args;
          existing.malformed = chunk.toolCall.malformed;
        }
      }
      if (chunk.type === 'done' && chunk.usage) {
        capturedUsage = {
          input: capturedUsage.input + (chunk.usage.promptTokens || 0),
          output: capturedUsage.output + (chunk.usage.completionTokens || 0),
          reasoning: capturedUsage.reasoning + (chunk.usage.reasoningTokens || 0),
          cached: capturedUsage.cached + (chunk.usage.cachedPromptTokens || 0),
        };
      }
    }

    contentText += roundContent;
    thinkingText += roundThinking;

    // E1: Early termination check — if the same skill is called for 3 consecutive rounds, force terminate
    // declare_case / declare_step are BATCH-DECLARATION tools: the LLM is SUPPOSED to call
    // declare_step repeatedly (once per step). Exclude them from the stuck-detection so the
    // loop isn't aborted mid-way through a tool-based declaration (a real failure that forced
    // the LLM to abandon Mode A and fall back to JSON).
    const nonDeclarationRecords = toolCallRecords.filter(
      (r) => r.name !== 'declare_case' && r.name !== 'declare_step',
    );
    if (nonDeclarationRecords.length >= 3) {
      const recentCalls = nonDeclarationRecords.slice(-3);
      const uniqueRecent = new Set(recentCalls.map(r => r.name));
      if (uniqueRecent.size === 1) {
        log.info(`Early termination: stuck repeating skill "${recentCalls[0].name}"`);
        break;
      }
    }

    if (pendingToolCalls.length === 0) {
      log.info(`Round ${round + 1}: no tool calls, exiting loop`);
      break;
    }

    log.info(`Round ${round + 1}: ${pendingToolCalls.length} tool calls: ${pendingToolCalls.map(tc => tc.name).join(', ')}`);

    // Filter out empty-named tool calls (hallucinated by some providers)
    const namedToolCalls = pendingToolCalls.filter(tc => tc.name);
    const skippedCount = pendingToolCalls.length - namedToolCalls.length;
    if (skippedCount > 0) log.warn(`Skipped ${skippedCount} tool call(s) with empty name`);

    if (namedToolCalls.length === 0) {
      log.info(`No named tool calls, exiting loop`);
      break;
    }

    // Execute tool calls
    const toolResults: ChatMessage[] = [];
    const criticalTools = new Set(['requirement_detail_query', 'istqb_guide', 'requirement_graph_query', 'flow_detail_query', 'html_knowledge_query']);
    
    for (const tc of namedToolCalls) {
      const skill = skillMap.get(tc.name);
      if (!skill) {
        log.warn(`Unknown tool call: ${tc.name}`);
        toolResults.push({ role: 'tool', content: JSON.stringify({ error: `Unknown tool: "${tc.name}". You can only call the tools explicitly provided to you. Do NOT invent or call any tool that is not in the available tool list. Continue your analysis in plain text and let the automatic extraction step produce the final structured output.` }, null, 2), toolCallId: tc.id });
        continue;
      }

      const skillStart = Date.now();
      try {
        let args = tc.args;
        if (typeof tc.args === 'string') {
          try {
            args = JSON.parse(tc.args);
          } catch (error) {
            // The HTML skill validates its own untrusted model input and returns
            // a bounded correction instead of turning malformed arguments into
            // a critical retrieval failure.
            if (tc.name !== 'html_knowledge_query') throw error;
          }
        }

        // Tool-schema validation at call time — only for declare_* tools.
        // Their enum/refine (verb whitelist, data-required, expectation coupling) MUST be
        // enforced HERE — otherwise invalid args reach declare-extract and only get
        // rejected later by validateStepContract, wasting the whole draft + a Phase 2
        // retry (real logs: "refresh browser page" non-vocab verb, fill-without-data,
        // element-state value "visible" all acked). Reject immediately with a clear
        // message so the LLM self-corrects in the next round.
        // Other skills (data queries, html_knowledge_query) intentionally handle their
        // own untrusted/malformed input leniently — do not gate them on schema here.
        const isDeclareTool = tc.name === 'declare_step' || tc.name === 'declare_case';
        const schemaCheck = isDeclareTool ? skill.schema?.safeParse(args) : undefined;
        if (schemaCheck && !schemaCheck.success) {
          const reasons = schemaCheck.error.issues
            .map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`)
            .join('; ');
          const message = `${tc.name} arguments rejected by schema: ${reasons}. Fix the arguments and call the tool again.`;
          log.warn(message);
          const toolCallRecord: ToolCallRecord = {
            name: tc.name,
            input: tc.args,
            output: { error: message },
            latencyMs: Date.now() - skillStart,
          };
          toolCallRecords.push(toolCallRecord);
          observer?.onToolCall?.(agentName, toolCallRecord);
          toolResults.push({ role: 'tool', content: JSON.stringify({ error: message }, null, 2), toolCallId: tc.id });
          observer?.onStep?.(agentName, round + 1, `${tc.name} args rejected`);
          continue;
        }

        const result = await skill.func(args as Record<string, unknown>);
        const latencyMs = Date.now() - skillStart;
        const serializedResult = serializeToolResult(result);
        const persisted = projectToolCallForState(skill, args, result, serializedResult.stateOutput, {
          latencyMs,
          resultSize: serializedResult.content.length,
        });
        log.kv(`${tc.name}`, `completed (${latencyMs}ms)`);
        const toolCallRecord: ToolCallRecord = {
          name: tc.name,
          input: persisted.input,
          output: persisted.output,
          latencyMs,
        };
        toolCallRecords.push(toolCallRecord);
        observer?.onToolCall?.(agentName, toolCallRecord);
        toolResults.push({ role: 'tool', content: truncateToolResult(serializedResult.content), toolCallId: tc.id });
        observer?.onStep?.(agentName, round + 1, `Called ${tc.name} (${latencyMs}ms)`);
      } catch (err: any) {
        const latencyMs = Date.now() - skillStart;
        log.error(`Skill ${tc.name} FAILED (${latencyMs}ms): ${err.message}`);

        if (err instanceof ToolStateProjectionError) throw err;
        
        // Critical Tool Failure - Abort immediately instead of letting the LLM hallucinate
        if (criticalTools.has(tc.name)) {
          log.error(`CRITICAL TOOL FAILURE: ${tc.name} failed. Aborting ReAct loop to prevent hallucination.`);
          throw new Error(`Critical tool execution failed: [${tc.name}] ${err.message}. Aborting to prevent context hallucination.`);
        }

        const toolCallRecord: ToolCallRecord = {
          name: tc.name,
          input: tc.args,
          output: { error: err.message },
          latencyMs,
        };
        toolCallRecords.push(toolCallRecord);
        observer?.onToolCall?.(agentName, toolCallRecord);
        toolResults.push({ role: 'tool', content: JSON.stringify({ error: err.message }, null, 2), toolCallId: tc.id });
      }
    }

    // Append assistant message (with tool_calls) + tool results
    allMessages.push({
      role: 'assistant',
      content: roundContent || null as any,
      toolCalls: namedToolCalls.map((tc) => ({
        type: 'function' as const,
        function: { name: tc.name, arguments: typeof tc.args === 'string' ? tc.args : JSON.stringify(tc.args) },
        id: tc.id,
      })),
    });

    allMessages.push(...toolResults);
  }

  const toolCallCount = toolCallRecords.length;
  observer?.onStep?.(agentName, 1, toolCallCount > 0
    ? `Phase 1: Analysis completed (${totalRounds} rounds, ${toolCallCount} tools)`
    : `Phase 1: Analysis completed (${totalRounds} rounds)`);

  return { contentText, thinkingText, toolCallRecords, usage: capturedUsage, conversationMessages: allMessages };
}

// ============================================================
// Targeted schema repair — 定点修复，替代"整体重新生成"
//
// 业界（Anthropic/OpenAI structured outputs）靠 API 层 constrained decoding 从根上
// 消灭 schema 违规。本项目 openai-compatible provider 因兼容性故意降级到 json_object
//（无 schema 约束），所以 zod 后校验仍会失败。此时不要"贴完整 schema/错误列表 + 让
// 模型从头重生成整个对象"，而是只把**出错字段的 path + 原因**反馈回去，让模型在
// 上一份 JSON 上做最小改动——同时省 input token（精简反馈）与 output token（最小改动）。
// ============================================================

interface ZodIssueLike {
  path?: Array<string | number>;
  message?: string;
}

function extractRepairIssues(error: unknown, maxIssues = 8): string[] {
  const issues = (error as { issues?: ZodIssueLike[] } | null | undefined)?.issues ?? [];
  const lines: string[] = [];
  const seen = new Set<string>();
  for (const issue of issues) {
    const path = (issue.path ?? []).join('.') || '(root)';
    const message = issue.message ?? 'invalid value';
    const key = `${path}:${message}`;
    if (seen.has(key)) continue;
    seen.add(key);
    lines.push(`- ${path}: ${message}`);
    if (lines.length >= maxIssues) break;
  }
  return lines;
}

function buildSchemaRepairFeedback(extractContent: string, schemaErr: unknown): ChatMessage[] {
  const lines = extractRepairIssues(schemaErr);
  const repairPrompt = [
    'The JSON you produced is valid JSON, but it failed schema validation on these fields:',
    ...lines,
    '',
    'Fix ONLY the fields listed above. Keep every other field and value exactly as you wrote them. Output the complete corrected JSON object with no text before or after it.',
  ].join('\n');
  return [
    { role: 'assistant' as const, content: extractContent },
    { role: 'user' as const, content: repairPrompt },
  ];
}

// ============================================================
// Main Entry: callLLMWithStructuredOutput
// ============================================================

/**
 * Call the LLM using a two-phase strategy:
 *   Phase 1: ReAct Loop — thinking + tool calls (if skills exist)
 *   Phase 2: Extraction — if Phase 1 does not produce valid JSON, make a second call to extract the structured output
 */
export async function callLLMWithStructuredOutput<T>(
  provider: AIProvider,
  messages: ChatMessage[],
  skills: SkillDefinition[],
  outputProfile: StructuredOutputProfile<T>,
  observer?: {
    onStep?: (name: string, idx: number, step: string) => void;
    onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void;
    onToolCall?: (name: string, toolCall: ToolCallRecord) => void;
  },
  agentName?: string,
  extra?: Partial<ChatOptions>,
): Promise<{ output: T; usage: { input: number; output: number; reasoning: number; cached: number }; toolCallRecords?: ToolCallRecord[] }> {
  const name = agentName ?? '';

  // ── Phase 1: ReAct Loop ──
  const reactResult = await runAgentReActLoop(
    provider,
    messages,
    skills,
    outputProfile,
    {
      onStep: observer?.onStep,
      onThinking: observer?.onThinking,
      onToolCall: observer?.onToolCall,
    },
    name,
    extra,
  );

  const { contentText, thinkingText, toolCallRecords, usage: capturedUsage, conversationMessages } = reactResult;

  if (!contentText && !thinkingText) {
    throw new Error('LLM produced no content in thinking phase');
  }

  const llmLog = Log.for(`llm:${name}`);

  // ── Phase 1-declare-extract ─────────────────────────────────────────────
  // Tool Use 强制结构化输出：如果 LLM 在 ReAct 中调用了 declare_case / declare_step
  // 工具，从 toolCallRecords 收集并拼成符合 DesignerRuntimeSchema 的 JSON。
  // verb 在工具层已由 enum 强制 → LLM 不可能写出非词表 action。
  const declareResult = tryExtractFromDeclareTools(toolCallRecords, contentText, name);
  if (declareResult) {
    try {
      const normalized = outputProfile.normalize(declareResult);
      const result = outputProfile.parse(normalized);
      llmLog.success('Phase 1 declare-extract valid ── skipping JSON extraction');
      observer?.onStep?.(name, 2, 'Phase 1: Declare-tool extraction success');
      return { output: result, usage: capturedUsage, toolCallRecords };
    } catch (parseErr: any) {
      const fullError = outputProfile.formatValidationError(parseErr);
      llmLog.warn(`Phase 1 declare-extract schema validation failed:\n${fullError}\n  → falling back to JSON extraction`);
    }
  }

  let phase1FailReason = 'no contentText';

  if (contentText) {
    const extracted = tryExtractJson(contentText);
    if (extracted) {
      if (outputProfile.shouldAttemptPhase1Extraction && !outputProfile.shouldAttemptPhase1Extraction(extracted)) {
        const { type: extractedType, keys } = extractedValueSummary(extracted);
        phase1FailReason = `unexpected wrapper (type=${extractedType}, keys=[${keys.join(',')}])`;
        llmLog.info(`Phase 1 JSON skipped ── ${phase1FailReason}`);
      } else {
      try {
        const normalized = outputProfile.normalize(extracted);
        const result = outputProfile.parse(normalized);
        llmLog.success('Phase 1 JSON valid ── skipping Phase 2');
        observer?.onStep?.(name, 2, 'Phase 1: Extraction direct success');
        return { output: result, usage: capturedUsage, toolCallRecords };
      } catch (parseErr: any) {
        const { type: extractedType, keys, draftTestCases: draftType } = extractedValueSummary(extracted);
        // Log the FULL validation error (not truncated) as an independent entry
        const fullError = outputProfile.formatValidationError(parseErr);
        phase1FailReason = `schema parse failed: ${fullError.split('\n')[0]}`;
        const errorBlock = [
          `Phase 1 JSON found but schema parse failed`,
          `  agent: ${name}`,
          `  extracted: type=${extractedType}, keys=[${keys.join(',')}], draftTestCases=${draftType}`,
          `  validation errors:`,
          ...fullError.split('\n').map(l => `    ${l}`),
        ].join('\n');
        llmLog.warn(errorBlock);
      }
      }
    } else {
      phase1FailReason = 'no JSON block found in contentText';
    }

  }

  // Phase 1.5: Nudge — if the LLM exited the ReAct loop without producing JSON,
  // send a follow-up in the SAME conversation (with full tool-result context)
  // asking it to output the final JSON. Phase 2 strips the conversation, losing
  // tool results — the nudge preserves them. Only triggers when no JSON was
  // found at all (not for schema-validation failures, which need Phase 2's
  // error-feedback loop).
  if (phase1FailReason === 'no JSON block found in contentText' && conversationMessages.length > 2) {
    llmLog.info('Phase 1.5: nudging LLM to output final JSON (full conversation context)');
    observer?.onStep?.(name, 2, 'Phase 1.5: Nudge for JSON output');

    const nudgeMessages: ChatMessage[] = [
      ...conversationMessages,
      { role: 'user' as const, content: buildExtractionPrompt(outputProfile) },
    ];

    const nudgeContent = await consumeExtractionStream(
      provider,
      nudgeMessages,
      buildExtractionChatOptions(outputProfile, extra),
      { onThinking: observer?.onThinking },
      name,
      capturedUsage,
    );

    if (nudgeContent) {
      const nudgeExtracted = tryExtractJson(nudgeContent);
      if (nudgeExtracted) {
        if (!outputProfile.shouldAttemptPhase1Extraction || outputProfile.shouldAttemptPhase1Extraction(nudgeExtracted)) {
          try {
            const normalized = outputProfile.normalize(nudgeExtracted);
            const result = outputProfile.parse(normalized);
            llmLog.success('Phase 1.5 JSON valid ── skipping Phase 2');
            observer?.onStep?.(name, 2, 'Phase 1.5: Nudge extraction success');
            return { output: result, usage: capturedUsage, toolCallRecords };
          } catch (parseErr: any) {
            const fullError = outputProfile.formatValidationError(parseErr);
            phase1FailReason = `Phase 1.5 schema parse failed: ${fullError.split('\n')[0]}`;
            llmLog.warn(`Phase 1.5 JSON found but schema parse failed:\n${fullError}`);
          }
        } else {
          const { keys } = extractedValueSummary(nudgeExtracted);
          llmLog.warn(`Phase 1.5 nudge produced unexpected wrapper (keys=[${keys.join(',')}])`);
        }
      } else {
        const preview = nudgeContent.length > 200 ? `${nudgeContent.slice(0, 200)}...` : nudgeContent;
        llmLog.warn(`Phase 1.5 nudge produced no parseable JSON ── length=${nudgeContent.length} ── preview: "${preview}"`);
      }
    } else {
      llmLog.warn('Phase 1.5 nudge produced no content');
    }
  }

  llmLog.info(`Phase 1 JSON invalid ── entering Phase 2 (schema extraction) ── reason: ${phase1FailReason}`);

  observer?.onStep?.(name, 2, 'Phase 2: Extracting structured output');

  // Phase 2: only send system + user + synthesized contentText + extraction prompt.
  // Skip all ReAct tool calls/results — contentText already synthesizes the findings
  // from tool calls. This avoids re-sending potentially large tool result payloads
  // (e.g., istqb_guide ~7k tokens, requirement_graph_query ~2k tokens per call).
  // Fallback: if contentText is too short (LLM put analysis in tool results, not content),
  // include the full conversation to preserve context.
  const PHASE2_MIN_CONTENT_LENGTH = 100;
  const useFullConversation = !contentText || contentText.length < PHASE2_MIN_CONTENT_LENGTH;

  let extractionMessages: ChatMessage[];
  if (useFullConversation) {
    llmLog.info(`Phase 2: contentText too short (${contentText.length} chars), using full conversation`);
    extractionMessages = [
      ...conversationMessages,
      { role: 'assistant' as const, content: contentText || '(analysis completed in earlier messages)' },
      { role: 'user' as const, content: buildExtractionPrompt(outputProfile) },
    ];
  } else {
    llmLog.info(`Phase 2: using condensed messages (system + user + contentText only), skipping ${conversationMessages.length - messages.length} ReAct messages`);
    extractionMessages = [
      ...messages,
      { role: 'assistant' as const, content: contentText },
      { role: 'user' as const, content: buildExtractionPrompt(outputProfile) },
    ];
  }

  const MAX_PHASE2_RETRIES = 2;
  let lastError: Error | null = null;
  const baseMessagesLength = extractionMessages.length;
  let lastErrorFeedback: ChatMessage[] | null = null;

  let lastExtractContent = '';

  for (let attempt = 1; attempt <= MAX_PHASE2_RETRIES; attempt++) {
    // Reset to base messages, then re-attach the most recent error feedback so
    // the LLM can self-correct on the next attempt (without unbounded token
    // growth from accumulating feedback across all retries).
    extractionMessages.splice(baseMessagesLength);
    if (lastErrorFeedback) {
      extractionMessages.push(...lastErrorFeedback);
    }

    if ((extra as any)?.signal?.aborted) {
      const reason: any = (extra as any)?.signal?.reason;
      const timedOut = reason != null && String(reason?.name) === 'TimeoutError';
      llmLog.error(`Phase 2 aborted on attempt ${attempt} (${timedOut ? 'timeout' : 'cancelled'})`);
      throw lastError || new Error(
        timedOut
          ? `Agent ${agentName || 'unknown'} timed out after ${(extra as any)?.timeoutMs ?? 'the configured'}ms`
          : 'Aborted',
      );
    }

    llmLog.info(`Phase 2 attempt ${attempt}/${MAX_PHASE2_RETRIES}`);
    observer?.onStep?.(name, 2, `Phase 2: Attempt ${attempt}/${MAX_PHASE2_RETRIES}`);
    const extractContent = await consumeExtractionStream(
      provider,
      extractionMessages,
      buildExtractionChatOptions(outputProfile, extra),
      { onThinking: observer?.onThinking },
      name,
      capturedUsage,
    );

    if (extractContent) {
      // Schema-constrained output should produce valid JSON, but still try parse with fallback
      const parsed = tryExtractJson(extractContent) ?? (() => {
        try { return JSON.parse(extractContent); } catch { return null; }
      })();

      if (parsed) {
        try {
          const result = outputProfile.parse(outputProfile.normalize(parsed));
          llmLog.success(`Phase 2 extraction successful on attempt ${attempt}`);
          observer?.onStep?.(name, 3, 'Phase 2: Extraction successful');
          return { output: result, usage: capturedUsage, toolCallRecords };
        } catch (schemaErr: any) {
          // Log the FULL validation error (not truncated) as an independent entry
          const fullError = outputProfile.formatValidationError(schemaErr);
          const errorBlock = [
            `Phase 2 schema validation failed on attempt ${attempt}`,
            `  agent: ${name}`,
            `  validation errors:`,
            ...fullError.split('\n').map(l => `    ${l}`),
          ].join('\n');
          llmLog.warn(errorBlock);
          // Attach the raw LLM content to the error so scope.ts can persist it
          // to error_raw_response for offline debugging.
          (schemaErr as any).rawResponse = extractContent;
          lastError = schemaErr;

          // 定点修复：只反馈出错字段（path + 原因），让模型在上一份 JSON 上最小改动，
          // 不再重发完整 schema/错误列表 + 整段重生成。
          lastErrorFeedback = buildSchemaRepairFeedback(extractContent, schemaErr);
        }
      } else {
        const preview = extractContent.length > 500 ? `${extractContent.slice(0, 500)}...` : extractContent;
        llmLog.warn(`Phase 2 produced unparseable content on attempt ${attempt} ── length=${extractContent.length} ── content preview: "${preview}"`);
        lastExtractContent = extractContent;
        lastError = new Error('Unparseable content');
        // Persist the raw content for offline debugging.
        (lastError as any).rawResponse = extractContent;

        lastErrorFeedback = [
          { role: 'assistant', content: extractContent },
          { role: 'user', content: 'The output was not valid JSON. Common issues: missing commas between properties, unquoted property names (use "key" not key), trailing commas before ] or }, or unclosed braces/brackets. Output a single valid JSON object matching the schema with no extra text.' },
        ];
      }
    } else {
      llmLog.warn(`Phase 2 produced no content on attempt ${attempt}`);
      lastError = new Error('No content produced');

      lastErrorFeedback = [
        { role: 'assistant', content: '(no output)' },
        { role: 'user', content: 'No content was generated. Please ensure you output a single valid JSON object matching the schema.' },
      ];
    }
  }

  if (lastExtractContent) {
    llmLog.error(`Last Phase 2 content (full):\n${lastExtractContent}`);
  }
  llmLog.error(`FAILED to extract structured output after ${MAX_PHASE2_RETRIES} attempts`);
  observer?.onStep?.(name, 3, 'Phase 2: Extraction failed');
  throw lastError || new Error('Failed to extract structured output from LLM response');
}
