import type { AIProvider, ChatMessage, ChatOptions, ToolCall } from '../../infra/provider.ts';
import type { SkillDefinition, ToolCallRecord } from './types.ts';
import type { SkillCallRecord } from '../state.ts';
import type { StructuredOutputProfile } from '../structured-output/profile.ts';
import { Log } from '../../../../shared/services/logger.ts';
import { zodToJsonSchema, makeSchemaOpenAICompatible } from './json-schema.ts';
import { tryExtractJson } from './json-extract.ts';
import { compactReActConversation } from './react-context.ts';
import { tryExtractFromEmitTools } from './emit-extract.ts';
import { extractRepairGaps, formatRepairPlan, type RepairGap } from '../structured-output/repair-plan.ts';
import { recordFailure, recordFailureFromZod, structuredModeFor } from '../../infra/failure-telemetry.ts';

// Re-export the schema/JSON/emit utilities so existing importers (structured-
// output profiles, tests) keep resolving them from `utils.ts`.
export { zodToJsonSchema, makeSchemaOpenAICompatible, compactReActConversation, tryExtractFromEmitTools };

/**
 * Provider reported finishReason === 'length': the output was cut off by
 * max_tokens. Retrying the same prompt only truncates again — the caller
 * (orchestrator) must shrink the batch instead of re-entering the retry loop.
 */
export class TruncatedOutputError extends Error {
  constructor(readonly agent: string, readonly phase: string, readonly partialLength: number) {
    super(`[${agent}] ${phase} output truncated by max_tokens (${partialLength} chars). Retry with a smaller batch — re-sending the same prompt will truncate again.`);
    this.name = 'TruncatedOutputError';
  }
}

/**
 * Compress repeated tool names into "name ×N" (order of first appearance).
 * ReAct rounds with batched emit_case would otherwise print
 * the same name 10+ times per line.
 */
export function summarizeToolNames(names: string[]): string {
  const counts = new Map<string, number>();
  for (const n of names) counts.set(n, (counts.get(n) ?? 0) + 1);
  return [...counts].map(([n, c]) => (c > 1 ? `${n} ×${c}` : n)).join(', ');
}

/**
 * Project raw ReAct tool-call records into the state's `skillCalls` channel.
 * Every agent node persists the same shape, so this lives in one place.
 */
export function toSkillCallRecords(
  agentName: string,
  toolCallRecords: ToolCallRecord[] | undefined,
): SkillCallRecord[] {
  return (toolCallRecords ?? []).map((tc) => ({
    agent: agentName,
    skillName: tc.name,
    input: tc.input,
    output: tc.output,
    latencyMs: tc.latencyMs,
    timestamp: Date.now(),
  }));
}

/**
 * Convert SkillDefinition[] to ChatOptions.tools format
 */
export function skillsToChatTools(skills: SkillDefinition[]): ChatOptions['tools'] {
  if (!skills || skills.length === 0) return undefined;
  return skills.map((s) => ({
    name: s.name,
    description: s.description,
    parameters: zodToJsonSchema(s.schema) as any,
  }));
}

/**
 * Strip fields the builder always overrides (temperature/responseFormat/tools/
 * toolChoice) from `extra`, so per-call overrides never resurrect a value the
 * Phase 1 / Phase 2 options explicitly control.
 */
function stripOptionOverrides(extra?: Partial<ChatOptions>): Partial<ChatOptions> {
  const { temperature: _temperature, responseFormat: _responseFormat, tools: _tools, toolChoice: _toolChoice, ...rest } = extra ?? {};
  return rest;
}

/** Phase 1 (ReAct) temperature — exported so ARCHITECTURE.md can bind to it. */
export const PHASE1_TEMPERATURE = 0.5;
/** Phase 2 (extraction) temperature — exported so ARCHITECTURE.md can bind to it. */
export const PHASE2_TEMPERATURE = 0;

/**
 * Build ChatOptions: Phase 1 thinking + ReAct stage
 * Only expose business tools; final structured output is generated by the subsequent extraction stage.
 */
export function buildThinkingChatOptions(
  skills: SkillDefinition[],
  extra?: Partial<ChatOptions>,
): ChatOptions {
  const allowedExtra = stripOptionOverrides(extra);
  
  // Build tool list: only business skills. Final JSON is generated by the subsequent extraction stage to avoid the thinking stage depending on the model proactively submitting a structured payload.
  const businessTools = skillsToChatTools(skills);
  
  return {
    temperature: PHASE1_TEMPERATURE,
    tools: businessTools,
    toolChoice: businessTools && businessTools.length > 0 ? 'auto' : undefined,
    ...allowedExtra,
  };
}

/**
 * Build ChatOptions: Phase 2 extraction stage, using json_schema response_format
 */
export function buildExtractionChatOptions(
  outputProfile: StructuredOutputProfile<unknown>,
  extra?: Partial<ChatOptions>,
): ChatOptions {
  const allowedExtra = stripOptionOverrides(extra);
  return {
    jsonSchema: outputProfile.toolSchema,
    temperature: PHASE2_TEMPERATURE,
    ...allowedExtra,
  };
}

/**
 * Build the Phase 2 extraction prompt, including schema constraints and the
 * compact ground-truth fact block (F5) the runtime cross-field validation
 * checks against.
 */
export function buildExtractionPrompt(outputProfile: StructuredOutputProfile<unknown>): string {
  const schema = outputProfile.toolSchema;
  const hints = outputProfile.extractionHints;
  const hintsSection = hints ? `\n\nAdditional constraints (JSON Schema cannot express these — follow strictly):\n${hints}` : '';
  const contextSection = outputProfile.extractionContext
    ? `\n\nGround-truth facts (validate against these — do NOT invent ids):\n${outputProfile.extractionContext}`
    : '';
  return `Based on the analysis above, output a single JSON object matching this schema. Do NOT include any text before or after the JSON.

Schema:
${JSON.stringify(schema, null, 2)}${hintsSection}${contextSection}`;
}

// ============================================================
// ReAct Loop
// ============================================================

const MAX_REACT_ROUNDS = 30;

// E3: Truncate large tool results to avoid context bloat
const MAX_TOOL_RESULT_CHARS = 6000;
function truncateToolResult(content: string): string {
  if (!content || typeof content !== 'string') return '';
  if (content.length <= MAX_TOOL_RESULT_CHARS) return content;
  return content.slice(0, MAX_TOOL_RESULT_CHARS) + `\n...(truncated, ${content.length} chars total)`;
}

function serializeToolArgs(args: unknown): string {
  if (args === undefined || args === null) return '';
  if (typeof args === 'string') return args;
  try {
    const s = JSON.stringify(args);
    return typeof s === 'string' ? s : '';
  } catch {
    return '';
  }
}

export class ToolStateProjectionError extends Error {
  constructor() {
    super('Tool state projection failed');
    this.name = 'ToolStateProjectionError';
  }
}

function serializeToolResult(result: unknown): { content: string; stateOutput: unknown } {
  if (typeof result === 'string') return { content: result, stateOutput: result };
  try {
    const content = JSON.stringify(result, null, 2);
    return typeof content === 'string'
      ? { content, stateOutput: JSON.parse(content) }
      : { content: 'null', stateOutput: null };
  } catch {
    return { content: 'null', stateOutput: null };
  }
}

function projectToolCallForState(
  skill: SkillDefinition,
  input: unknown,
  result: unknown,
  stateOutput: unknown,
  meta: { latencyMs: number; resultSize: number },
): { input: unknown; output: unknown } {
  if (!skill.summarizeForState) return { input, output: stateOutput };

  let projection: unknown;
  try {
    projection = skill.summarizeForState(input, result, meta);
  } catch {
    throw new ToolStateProjectionError();
  }
  let normalizedProjection: unknown;
  try {
    const serialized = JSON.stringify(projection);
    if (serialized === undefined) throw new ToolStateProjectionError();
    normalizedProjection = JSON.parse(serialized);
  } catch {
    throw new ToolStateProjectionError();
  }
  if (!normalizedProjection
    || typeof normalizedProjection !== 'object'
    || Array.isArray(normalizedProjection)
    || !Object.hasOwn(normalizedProjection, 'input')
    || !Object.hasOwn(normalizedProjection, 'output')) {
    throw new ToolStateProjectionError();
  }
  return normalizedProjection as { input: unknown; output: unknown };
}

function extractedValueSummary(value: unknown): { type: string; keys: string[]; draftTestCases: string } {
  const keys = value && typeof value === 'object' ? Object.keys(value as Record<string, unknown>) : [];
  const draftTestCases = (value as any)?.draftTestCases ? typeof (value as any).draftTestCases : 'missing';
  return { type: typeof value, keys, draftTestCases };
}

/**
 * Consume an extraction-stage stream (Phase 1.5 nudge / Phase 2 retry loop),
 * accumulating content, token usage and the provider finishReason.
 * finishReason === 'length' means the output was truncated by max_tokens —
 * surfaced so callers can distinguish truncation from schema failures
 * (retrying a truncated prompt only truncates again).
 */
interface ExtractStreamResult {
  content: string;
  finishReason?: string;
}

async function consumeExtractionStream(
  provider: AIProvider,
  messages: ChatMessage[],
  options: ChatOptions,
  observer: { onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void },
  name: string,
  usage: { input: number; output: number; reasoning: number; cached: number },
): Promise<ExtractStreamResult> {
  let content = '';
  let finishReason: string | undefined;
  for await (const chunk of provider.streamChat(messages, options)) {
    if (chunk.type === 'content' && chunk.content) {
      content += chunk.content;
      observer?.onThinking?.(name, chunk.content, 'content', 'extraction');
    }
    if (chunk.type === 'done') {
      if (chunk.usage) {
        usage.input += (chunk.usage.promptTokens || 0);
        usage.output += (chunk.usage.completionTokens || 0);
        usage.reasoning += (chunk.usage.reasoningTokens || 0);
        usage.cached += (chunk.usage.cachedPromptTokens || 0);
      }
      finishReason = chunk.finishReason;
    }
  }
  return { content, finishReason };
}

interface ReActResult {
  contentText: string;
  thinkingText: string;
  toolCallRecords: ToolCallRecord[];
  usage: { input: number; output: number; reasoning: number; cached: number };
  conversationMessages: ChatMessage[];
}

/**
 * Execute the ReAct loop: LLM thinks → call tool → observe result → continue thinking
 * At most MAX_REACT_ROUNDS rounds; exit when there are no tool_calls
 */
async function runAgentReActLoop(
  provider: AIProvider,
  messages: ChatMessage[],
  skills: SkillDefinition[],
  outputProfile: StructuredOutputProfile<unknown>,
  observer: {
    onStep?: (name: string, idx: number, step: string) => void;
    onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void;
    onToolCall?: (name: string, toolCall: ToolCallRecord) => void;
  },
  agentName: string,
  extra: Partial<ChatOptions> | undefined,
): Promise<ReActResult> {
  const skillMap = new Map(skills.map((s) => [s.name, s]));
  const log = Log.for(`react:${agentName}`);
  log.info(`ReAct loop start ── ${skills.length} skills: ${skills.map(s => s.name).join(', ')}`);
  const allMessages: ChatMessage[] = [...messages];
  let contentText = '';
  let thinkingText = '';
  const toolCallRecords: ReActResult['toolCallRecords'] = [];
  let capturedUsage = {
    input: 0,
    output: 0,
    reasoning: 0,
    cached: 0,
  };
  let totalRounds = 0;

  observer?.onStep?.(agentName, 0, 'Phase 1: Analysis started');

  for (let round = 0; round < MAX_REACT_ROUNDS; round++) {
    totalRounds = round + 1;
    // Stream call to LLM (with tools)
    let roundContent = '';
    let roundThinking = '';
    const pendingToolCalls: ToolCall[] = [];

    // 上下文窗口压缩：只发送 base + 最近几轮完整消息，更早轮次的工具结果摘要化，
    // 防止每轮重发全部历史导致 O(n²) token 膨胀（实测 Designer 单 run input 260k tokens）。
    const sendMessages = compactReActConversation(allMessages, messages.length);

    for await (const chunk of provider.streamChat(sendMessages, buildThinkingChatOptions(skills, extra))) {
      if (chunk.type === 'reasoning' && chunk.content) {
        roundThinking += chunk.content;
        observer?.onThinking?.(agentName, chunk.content, 'reasoning', 'react');
      }
      if (chunk.type === 'content' && chunk.content) {
        roundContent += chunk.content;
        observer?.onThinking?.(agentName, chunk.content, 'content', 'react');
      }
      if (chunk.type === 'tool_call_start' && chunk.toolCall) {
        pendingToolCalls.push(chunk.toolCall);
      }
      if (chunk.type === 'tool_call_delta' && chunk.toolCall) {
        const existing = pendingToolCalls.find((tc) => tc.id === chunk.toolCall!.id);
        if (existing) {
          existing.args = chunk.toolCall.args; // The last delta contains the complete args
        } else {
          pendingToolCalls.push(chunk.toolCall);
        }
      }
      if (chunk.type === 'tool_call_end' && chunk.toolCall) {
        const existing = pendingToolCalls.find((tc) => tc.id === chunk.toolCall!.id);
        if (existing) {
          existing.args = chunk.toolCall.args;
          existing.malformed = chunk.toolCall.malformed;
        }
      }
      if (chunk.type === 'done' && chunk.usage) {
        capturedUsage = {
          input: capturedUsage.input + (chunk.usage.promptTokens || 0),
          output: capturedUsage.output + (chunk.usage.completionTokens || 0),
          reasoning: capturedUsage.reasoning + (chunk.usage.reasoningTokens || 0),
          cached: capturedUsage.cached + (chunk.usage.cachedPromptTokens || 0),
        };
      }
    }

    contentText += roundContent;
    thinkingText += roundThinking;

    // E1: Early termination check — if the same skill is called for 3 consecutive rounds, force terminate
    // emit_* are BATCH-DECLARATION tools: the LLM is SUPPOSED to call them
    // repeatedly (once per case/condition). Exclude them from the stuck-detection so the
    // loop isn't aborted mid-way through a tool-based declaration (a real failure that forced
    // the LLM to abandon Mode A and fall back to JSON).
    const nonDeclarationRecords = toolCallRecords.filter(
      (r) => !r.name.startsWith('emit_'),
    );
    if (nonDeclarationRecords.length >= 3) {
      const recentCalls = nonDeclarationRecords.slice(-3);
      const uniqueRecent = new Set(recentCalls.map(r => r.name));
      // Only treat as "stuck" if the SAME skill is called 3 times with IDENTICAL args.
      // E.g. istqb_guide loaded for 3 different techniques (3 different technique sets)
      // is legitimate exploration, not a stuck loop — killing it here caused analyst to
      // abandon emit_condition (zero conditions were ever emitted in the failing run).
      const allSameArgs = recentCalls.every((r) =>
        JSON.stringify(r.input) === JSON.stringify(recentCalls[0].input),
      );
      if (uniqueRecent.size === 1 && allSameArgs) {
        log.info(`Early termination: stuck repeating skill "${recentCalls[0].name}"`);
        break;
      }
    }

    if (pendingToolCalls.length === 0) {
      log.info(`Round ${round + 1}: no tool calls, exiting loop`);
      break;
    }

    log.info(`Round ${round + 1}: ${pendingToolCalls.length} tool calls: ${summarizeToolNames(pendingToolCalls.map(tc => tc.name))}`);

    // Filter out empty-named tool calls (hallucinated by some providers)
    const namedToolCalls = pendingToolCalls.filter(tc => tc.name);
    const skippedCount = pendingToolCalls.length - namedToolCalls.length;
    if (skippedCount > 0) log.warn(`Skipped ${skippedCount} tool call(s) with empty name`);

    if (namedToolCalls.length === 0) {
      log.info(`No named tool calls, exiting loop`);
      break;
    }

    // Execute tool calls
    const toolResults: ChatMessage[] = [];
    const criticalTools = new Set(['requirement_detail_query', 'istqb_guide', 'requirement_graph_query', 'flow_detail_query', 'html_knowledge_query']);
    // emit_* 调用按批合并日志（LLM 常在一轮内连发 10+ 次，逐条打印会刷屏）
    const emitIdsByTool = new Map<string, string[]>();

    for (const tc of namedToolCalls) {
      const skill = skillMap.get(tc.name);
      if (!skill) {
        log.warn(`Unknown tool call: ${tc.name}`);
        toolResults.push({ role: 'tool', content: JSON.stringify({ error: `Unknown tool: "${tc.name}". You can only call the tools explicitly provided to you. Do NOT invent or call any tool that is not in the available tool list. Continue your analysis in plain text and let the automatic extraction step produce the final structured output.` }, null, 2), toolCallId: tc.id });
        continue;
      }

      const skillStart = Date.now();
      try {
        let args = tc.args;
        if (typeof tc.args === 'string') {
          try {
            args = JSON.parse(tc.args);
          } catch (error) {
            // The HTML skill validates its own untrusted model input and returns
            // a bounded correction instead of turning malformed arguments into
            // a critical retrieval failure.
            if (tc.name !== 'html_knowledge_query') throw error;
          }
        }

        // Tool-schema validation at call time — only for emit_case.
        // Its enum/refine (verb whitelist, data-required, expectation coupling) MUST be
        // enforced HERE — otherwise invalid args reach emit-extract and only get
        // rejected later by validateStepContract, wasting the whole draft + a Phase 2
        // retry (real logs: "refresh browser page" non-vocab verb, fill-without-data,
        // element-state value "visible" all acked). Reject immediately with a clear
        // message so the LLM self-corrects in the next round.
        // Other skills (data queries, html_knowledge_query) intentionally handle their
        // own untrusted/malformed input leniently — do not gate them on schema here.
        const isEmitTool = tc.name.startsWith('emit_');
        const schemaCheck = isEmitTool ? skill.schema?.safeParse(args) : undefined;
        if (schemaCheck && !schemaCheck.success) {
          const reasons = schemaCheck.error.issues
            .map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`)
            .join('; ');
          const message = `${tc.name} arguments rejected by schema: ${reasons}. Fix the arguments and call the tool again.`;
          log.warn(message);
          const toolCallRecord: ToolCallRecord = {
            name: tc.name,
            input: tc.args,
            output: { error: message },
            latencyMs: Date.now() - skillStart,
          };
          toolCallRecords.push(toolCallRecord);
          observer?.onToolCall?.(agentName, toolCallRecord);
          toolResults.push({ role: 'tool', content: JSON.stringify({ error: message }, null, 2), toolCallId: tc.id });
          observer?.onStep?.(agentName, round + 1, `${tc.name} args rejected`);
          continue;
        }

        const result = await skill.func(args as Record<string, unknown>);
        const latencyMs = Date.now() - skillStart;
        const serializedResult = serializeToolResult(result);
        const persisted = projectToolCallForState(skill, args, result, serializedResult.stateOutput, {
          latencyMs,
          resultSize: serializedResult.content.length,
        });
        if (isEmitTool) {
          const id = String((args as any)?.id ?? (args as any)?.caseId ?? (args as any)?.conditionId ?? '');
          if (id) {
            const list = emitIdsByTool.get(tc.name) ?? [];
            if (!list.includes(id)) list.push(id);
            emitIdsByTool.set(tc.name, list);
          }
        } else {
          log.kv(`${tc.name}`, `completed (${latencyMs}ms)`);
        }
        const toolCallRecord: ToolCallRecord = {
          name: tc.name,
          input: persisted.input,
          output: persisted.output,
          latencyMs,
        };
        toolCallRecords.push(toolCallRecord);
        observer?.onToolCall?.(agentName, toolCallRecord);
        toolResults.push({ role: 'tool', content: truncateToolResult(serializedResult.content), toolCallId: tc.id });
        observer?.onStep?.(agentName, round + 1, `Called ${tc.name} (${latencyMs}ms)`);
      } catch (err: any) {
        const latencyMs = Date.now() - skillStart;
        log.error(`Skill ${tc.name} FAILED (${latencyMs}ms): ${err.message}`);

        if (err instanceof ToolStateProjectionError) throw err;
        
        // Critical Tool Failure - Abort immediately instead of letting the LLM hallucinate
        if (criticalTools.has(tc.name)) {
          log.error(`CRITICAL TOOL FAILURE: ${tc.name} failed. Aborting ReAct loop to prevent hallucination.`);
          throw new Error(`Critical tool execution failed: [${tc.name}] ${err.message}. Aborting to prevent context hallucination.`);
        }

        const toolCallRecord: ToolCallRecord = {
          name: tc.name,
          input: tc.args,
          output: { error: err.message },
          latencyMs,
        };
        toolCallRecords.push(toolCallRecord);
        observer?.onToolCall?.(agentName, toolCallRecord);
        toolResults.push({ role: 'tool', content: JSON.stringify({ error: err.message }, null, 2), toolCallId: tc.id });
      }
    }

    for (const [toolName, ids] of emitIdsByTool) {
      const range = ids.length > 1 ? ` (${ids[0]}..${ids[ids.length - 1]})` : '';
      log.kv('emit', `${toolName} ×${ids.length} acked${range}`);
    }

    // Append assistant message (with tool_calls) + tool results
    allMessages.push({
      role: 'assistant',
      content: roundContent || null as any,
      toolCalls: namedToolCalls.map((tc) => ({
        type: 'function' as const,
        function: { name: tc.name, arguments: serializeToolArgs(tc.args) },
        id: tc.id,
      })),
    });

    allMessages.push(...toolResults);
  }

  const toolCallCount = toolCallRecords.length;
  observer?.onStep?.(agentName, 1, toolCallCount > 0
    ? `Phase 1: Analysis completed (${totalRounds} rounds, ${toolCallCount} tools)`
    : `Phase 1: Analysis completed (${totalRounds} rounds)`);

  return { contentText, thinkingText, toolCallRecords, usage: capturedUsage, conversationMessages: allMessages };
}

// ============================================================
// Targeted schema repair — 定点修复，替代"整体重新生成"
//
// 业界（Anthropic/OpenAI structured outputs）靠 API 层 constrained decoding 从根上
// 消灭 schema 违规。本项目 openai-compatible provider 因兼容性故意降级到 json_object
//（无 schema 约束），所以 zod 后校验仍会失败。此时不要"贴完整 schema/错误列表 + 让
// 模型从头重生成整个对象"，而是只把**出错字段的 path + 原因**反馈回去，让模型在
// 上一份 JSON 上做最小改动——同时省 input token（精简反馈）与 output token（最小改动）。
// ============================================================

interface ZodIssueLike {
  path?: Array<string | number>;
  message?: string;
}

function extractRepairIssues(error: unknown, maxIssues = 8): string[] {
  const issues = (error as { issues?: ZodIssueLike[] } | null | undefined)?.issues ?? [];
  const lines: string[] = [];
  const seen = new Set<string>();
  for (const issue of issues) {
    const path = (issue.path ?? []).join('.') || '(root)';
    const message = issue.message ?? 'invalid value';
    const key = `${path}:${message}`;
    if (seen.has(key)) continue;
    seen.add(key);
    lines.push(`- ${path}: ${message}`);
    if (lines.length >= maxIssues) break;
  }
  return lines;
}

function buildSchemaRepairFeedback(extractContent: string, schemaErr: unknown): ChatMessage[] {
  const lines = extractRepairIssues(schemaErr);
  const repairPrompt = [
    'The JSON you produced is valid JSON, but it failed schema validation on these fields:',
    ...lines,
    '',
    'Fix ONLY the fields listed above. Keep every other field and value exactly as you wrote them. Output the complete corrected JSON object with no text before or after it.',
  ].join('\n');
  return [
    { role: 'assistant' as const, content: extractContent },
    { role: 'user' as const, content: repairPrompt },
  ];
}

// ============================================================
// Phase 1.25 emit-repair — 复用已声明的 emit_* 实体，定点修补
//
// emit 模式的核心优势：实体已通过 toolCallRecords 落盘。跨字段校验失败时，
// 不再落整批 Phase 2 全量 JSON 重发（烧全量 output token），而是把错误回投进
// 同一会话、只开放 emit_* 工具，让 LLM 重发坏掉的实体（last-write-wins 覆盖），
// 再 merge 重提取。修复成本 ≈ 坏实体数 × 单条调用，远小于整批重生成。
// ============================================================

/** 用结构化缺口清单替代报错原文：已声明 id + 每条缺口的可执行修复指令。 */
function buildRepairPrompt(existingRecords: ToolCallRecord[], gaps: RepairGap[], fallbackErrorText: string): string {
  const declaredIds = [...new Set(
    existingRecords
      .filter((r) => r.name.startsWith('emit_'))
      .map((r) => String((r.input as any)?.id ?? (r.input as any)?.caseId ?? (r.input as any)?.conditionId ?? '').trim())
      .filter(Boolean),
  )];

  const gapLines = gaps.slice(0, 12).map((g) =>
    `- [${g.type}] ${g.entityId}${g.field ? ` (${g.field})` : ''}${g.badValue ? ` — bad value "${g.badValue}"` : ''} → ${g.fix}`,
  );

  const lines = [
    'Your emitted entities failed validation. Re-emit ONLY the entities with gaps below via the matching `emit_*` tool (same id overwrites the previous declaration).',
    '',
    `Already declared entities: ${declaredIds.length > 0 ? declaredIds.join(', ') : '(none)'}`,
    '',
    `Gaps to fix (${gaps.length}):`,
  ];
  if (gapLines.length > 0) {
    lines.push(...gapLines);
  } else {
    lines.push(...fallbackErrorText.split('\n').slice(0, 14).map((l) => `  ${l}`));
  }
  lines.push('', 'Leave every passing entity untouched. Do NOT emit a JSON block. Stop after re-emitting the fixes.');
  return lines.join('\n');
}

/** 定向补缺：只列缺失实体（纯增量，最便宜），不发整批 schema、不重发已有实体。 */
function buildCompletionPrompt(missingGaps: RepairGap[]): string {
  return [
    'You are still MISSING some entities. Emit ONLY the missing entities below via the matching `emit_*` tool — do NOT re-emit anything you already emitted.',
    '',
    'Missing entities to add:',
    ...missingGaps.slice(0, 12).map((g) => `- ${g.fix}`),
    '',
    'Do NOT emit a JSON block. Stop after emitting the missing entities.',
  ].join('\n');
}

interface EmitRepairDeps<T> {
  provider: AIProvider;
  llmLog: ReturnType<typeof Log.for>;
  observer?: {
    onStep?: (name: string, idx: number, step: string) => void;
    onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void;
    onToolCall?: (name: string, toolCall: ToolCallRecord) => void;
  };
  name: string;
  agentName: string;
  extra?: Partial<ChatOptions>;
  skills: SkillDefinition[];
  outputProfile: StructuredOutputProfile<T>;
  parseErr: unknown;
  conversationMessages: ChatMessage[];
  existingRecords: ToolCallRecord[];
}

const MAX_EMIT_REPAIR_ROUNDS = 3;

async function runEmitRepair<T>(deps: EmitRepairDeps<T>): Promise<{ output: T; usage: { input: number; output: number; reasoning: number; cached: number }; toolCallRecords: ToolCallRecord[] } | null> {
  const { provider, llmLog, observer, name, agentName, extra, skills, outputProfile, parseErr, conversationMessages, existingRecords } = deps;
  // 只开放 emit_* 工具：修复轮不应再触发数据查询等重活。
  const emitSkills = skills.filter((s) => s.name.startsWith('emit_'));
  if (emitSkills.length === 0) return null;

  let records = [...existingRecords];
  let curConversation = [...conversationMessages];
  let curGaps = extractRepairGaps(parseErr);
  let curErrorText = outputProfile.formatValidationError(parseErr);

  const emitCount = existingRecords.filter((r) => r.name.startsWith('emit_')).length;
  llmLog.warn(`emit-repair attribution: ${formatRepairPlan({ mode: 'emit', emitCount, layer: 'global', gaps: curGaps })}`);

  for (let attempt = 1; attempt <= MAX_EMIT_REPAIR_ROUNDS; attempt++) {
    llmLog.info(`emit-repair attempt ${attempt}/${MAX_EMIT_REPAIR_ROUNDS} (skills: ${emitSkills.map((s) => s.name).join(', ')})`);
    observer?.onStep?.(name, 2, `Phase 1.25: Emit-repair attempt ${attempt}/${MAX_EMIT_REPAIR_ROUNDS}`);

    const repairPrompt = buildRepairPrompt(records, curGaps, curErrorText);

    const repairMessages: ChatMessage[] = [
      ...curConversation,
      { role: 'user' as const, content: repairPrompt },
    ];

    const repair = await runAgentReActLoop(
      provider,
      repairMessages,
      emitSkills,
      outputProfile,
      {
        onStep: observer?.onStep,
        onThinking: observer?.onThinking,
        onToolCall: observer?.onToolCall,
      },
      name,
      extra,
    );

    // 追加本轮新增的会话消息（供下一轮上下文）。
    curConversation = [...curConversation, ...repair.conversationMessages.slice(curConversation.length)];

    records = [...records, ...repair.toolCallRecords];
    const merged = outputProfile.emitExtract?.(records, repair.contentText, name) ?? null;
    if (!merged) {
      llmLog.warn(`emit-repair attempt ${attempt}: no valid entities assembled from repaired records`);
      continue;
    }
    try {
      const normalized = outputProfile.normalize(merged);
      const result = outputProfile.parse(normalized);
      llmLog.success(`emit-repair converged on attempt ${attempt}`);
      observer?.onStep?.(name, 2, 'Phase 1.25: Emit-repair success');
      return { output: result, usage: repair.usage, toolCallRecords: records };
    } catch (repairErr: any) {
      curErrorText = outputProfile.formatValidationError(repairErr);
      curGaps = extractRepairGaps(repairErr);
      llmLog.warn(`emit-repair attempt ${attempt} still invalid: ${curGaps.length} gap(s)\n${curErrorText.split('\n').slice(0, 6).join('\n')}`);
    }
  }

  // ── Phase 1.26 定向补缺 ──
  // 主循环收敛失败时，若缺口以"漏实体"为主（missing-entity），做一轮纯补缺而非
  // 直接落整批 Phase 2：只发"补这些缺失实体"的窄指令（纯增量、最便宜、最不易截断）。
  const missingGaps = curGaps.filter((g) => g.type === 'missing-entity');
  if (missingGaps.length > 0) {
    observer?.onStep?.(name, 2, 'Phase 1.26: Targeted completion');
    llmLog.info(`targeted completion: ${missingGaps.length} missing entity/entities`);

    const completionPrompt = buildCompletionPrompt(missingGaps);
    const completion = await runAgentReActLoop(
      provider,
      [...curConversation, { role: 'user' as const, content: completionPrompt }],
      emitSkills,
      outputProfile,
      {
        onStep: observer?.onStep,
        onThinking: observer?.onThinking,
        onToolCall: observer?.onToolCall,
      },
      name,
      extra,
    );

    const completedRecords = [...records, ...completion.toolCallRecords];
    const completedMerged = outputProfile.emitExtract?.(completedRecords, completion.contentText, name) ?? null;
    if (completedMerged) {
      try {
        const result = outputProfile.parse(outputProfile.normalize(completedMerged));
        llmLog.success('Phase 1.26 targeted completion converged');
        observer?.onStep?.(name, 2, 'Phase 1.26: Targeted completion success');
        return { output: result, usage: completion.usage, toolCallRecords: completedRecords };
      } catch (err: any) {
        llmLog.warn(`Phase 1.26 completion still invalid: ${outputProfile.formatValidationError(err).split('\n')[0]}`);
      }
    }
  }

  return null;
}

// ============================================================
// Main Entry: callLLMWithStructuredOutput
// ============================================================

/**
 * Call the LLM using a two-phase strategy:
 *   Phase 1: ReAct Loop — thinking + tool calls (if skills exist)
 *   Phase 2: Extraction — if Phase 1 does not produce valid JSON, make a second call to extract the structured output
 */
export async function callLLMWithStructuredOutput<T>(
  provider: AIProvider,
  messages: ChatMessage[],
  skills: SkillDefinition[],
  outputProfile: StructuredOutputProfile<T>,
  observer?: {
    onStep?: (name: string, idx: number, step: string) => void;
    onThinking?: (name: string, text: string, type: 'reasoning' | 'content', phase: 'react' | 'extraction') => void;
    onToolCall?: (name: string, toolCall: ToolCallRecord) => void;
  },
  agentName?: string,
  extra?: Partial<ChatOptions>,
): Promise<{ output: T; usage: { input: number; output: number; reasoning: number; cached: number }; toolCallRecords?: ToolCallRecord[] }> {
  const name = agentName ?? '';

  // ── Phase 1: ReAct Loop ──
  const reactResult = await runAgentReActLoop(
    provider,
    messages,
    skills,
    outputProfile,
    {
      onStep: observer?.onStep,
      onThinking: observer?.onThinking,
      onToolCall: observer?.onToolCall,
    },
    name,
    extra,
  );

  const { contentText, thinkingText, toolCallRecords, usage: capturedUsage, conversationMessages } = reactResult;

  if (!contentText && !thinkingText) {
    throw new Error('LLM produced no content in thinking phase');
  }

  const llmLog = Log.for(`llm:${name}`);

// ── Phase 1-emit-extract ─────────────────────────────────────────────
  // Tool Use 强制结构化输出：如果 LLM 在 ReAct 中通过 emit_* 工具声明了
  // 结构化实体（如 designer 的 emit_case / quality 的 emit_review），由 profile 的
  // emitExtract 钩子从 toolCallRecords 收集并拼成待校验的 raw 结构。
  // verb 在工具层已由 enum 强制 → LLM 不可能写出非词表 action。
  let emitResult = outputProfile.emitExtract?.(toolCallRecords, contentText, name) ?? null;
  if (emitResult) {
    try {
      const normalized = outputProfile.normalize(emitResult);
      const result = outputProfile.parse(normalized);
      llmLog.success('Phase 1 emit-extract valid ── skipping JSON extraction');
      observer?.onStep?.(name, 2, 'Phase 1: Emit-tool extraction success');
      return { output: result, usage: capturedUsage, toolCallRecords };
    } catch (parseErr: any) {
      const fullError = outputProfile.formatValidationError(parseErr);
      llmLog.warn(`Phase 1 emit-extract schema validation failed:\n${fullError}`);
      recordFailureFromZod({
        agent: name,
        providerKind: provider.kind ?? 'unknown',
        structuredMode: 'none',
        failureType: 'SCHEMA',
        attempt: 0,
      }, parseErr);

      // ── Phase 1.25 emit-repair：复用已声明的实体，只重发坏掉的那几个 ──
      // 校验失败（通常是跨字段门：dependencies 假 ID、flow 覆盖不全、testLevel 漂移），
      // 不落整批 Phase 2 全量 JSON 重发，而是把错误回投进同一会话，只开放 emit_* 工具，
      // 让 LLM 重发坏掉的实体（last-write-wins 覆盖），再 merge 重提取。
      // 复用 toolCallRecords —— 这是 emit 模式相对整块 JSON 的核心优势。
      const repaired = await runEmitRepair({
        provider, llmLog, observer, name, extra, skills, outputProfile,
        parseErr,
        conversationMessages,
        existingRecords: toolCallRecords,
        agentName,
      });
      if (repaired) {
        return repaired;
      }
      recordFailure({
        agent: name,
        providerKind: provider.kind ?? 'unknown',
        structuredMode: 'none',
        failureType: 'EMIT_REPAIR_NOT_CONVERGED',
        attempt: 0,
      });
      llmLog.warn(`emit-repair did not converge → falling back to JSON extraction`);
    }
  }

  let phase1FailReason = 'no contentText';

  if (contentText) {
    const extracted = tryExtractJson(contentText, { allowTruncatedRepair: true });
    if (extracted) {
      if (outputProfile.shouldAttemptPhase1Extraction && !outputProfile.shouldAttemptPhase1Extraction(extracted)) {
        const { type: extractedType, keys } = extractedValueSummary(extracted);
        phase1FailReason = `unexpected wrapper (type=${extractedType}, keys=[${keys.join(',')}])`;
        llmLog.info(`Phase 1 JSON skipped ── ${phase1FailReason}`);
      } else {
      try {
        const normalized = outputProfile.normalize(extracted);
        const result = outputProfile.parse(normalized);
        llmLog.success('Phase 1 JSON valid ── skipping Phase 2');
        observer?.onStep?.(name, 2, 'Phase 1: Extraction direct success');
        return { output: result, usage: capturedUsage, toolCallRecords };
      } catch (parseErr: any) {
        const { type: extractedType, keys, draftTestCases: draftType } = extractedValueSummary(extracted);
        // Log the FULL validation error (not truncated) as an independent entry
        const fullError = outputProfile.formatValidationError(parseErr);
        phase1FailReason = `schema parse failed: ${fullError.split('\n')[0]}`;
        const errorBlock = [
          `Phase 1 JSON found but schema parse failed`,
          `  agent: ${name}`,
          `  extracted: type=${extractedType}, keys=[${keys.join(',')}], draftTestCases=${draftType}`,
          `  validation errors:`,
          ...fullError.split('\n').map(l => `    ${l}`),
        ].join('\n');
        llmLog.warn(errorBlock);
      }
      }
    } else {
      phase1FailReason = 'no JSON block found in contentText';
    }

  }

  // Phase 1.5: Nudge — if the LLM exited the ReAct loop without producing JSON,
  // send a follow-up in the SAME conversation (with full tool-result context)
  // asking it to output the final JSON. Phase 2 strips the conversation, losing
  // tool results — the nudge preserves them. Only triggers when no JSON was
  // found at all (not for schema-validation failures, which need Phase 2's
  // error-feedback loop).
  if (phase1FailReason === 'no JSON block found in contentText' && conversationMessages.length > 2) {
    llmLog.info('Phase 1.5: nudging LLM to output final JSON (full conversation context)');
    observer?.onStep?.(name, 2, 'Phase 1.5: Nudge for JSON output');

    const nudgeMessages: ChatMessage[] = [
      ...conversationMessages,
      { role: 'user' as const, content: buildExtractionPrompt(outputProfile) },
    ];

    const nudge = await consumeExtractionStream(
      provider,
      nudgeMessages,
      buildExtractionChatOptions(outputProfile, extra),
      { onThinking: observer?.onThinking },
      name,
      capturedUsage,
    );
    const nudgeContent = nudge.content;

    if (nudgeContent) {
      // 截断在严格提取路径同样无意义——同一个 prompt 重试只会再截断。
      // 抛出独立错误，让编排层缩小批次后重跑（F1 分流）。
      if (nudge.finishReason === 'length') {
        llmLog.warn(`Phase 1.5 nudge output truncated by max_tokens (${nudgeContent.length} chars) ── not retrying`);
        throw new TruncatedOutputError(name, 'phase1.5', nudgeContent.length);
      }
      const nudgeExtracted = tryExtractJson(nudgeContent, { allowTruncatedRepair: true });
      if (nudgeExtracted) {
        if (!outputProfile.shouldAttemptPhase1Extraction || outputProfile.shouldAttemptPhase1Extraction(nudgeExtracted)) {
          try {
            const normalized = outputProfile.normalize(nudgeExtracted);
            const result = outputProfile.parse(normalized);
            llmLog.success('Phase 1.5 JSON valid ── skipping Phase 2');
            observer?.onStep?.(name, 2, 'Phase 1.5: Nudge extraction success');
            return { output: result, usage: capturedUsage, toolCallRecords };
          } catch (parseErr: any) {
            const fullError = outputProfile.formatValidationError(parseErr);
            phase1FailReason = `Phase 1.5 schema parse failed: ${fullError.split('\n')[0]}`;
            llmLog.warn(`Phase 1.5 JSON found but schema parse failed:\n${fullError}`);
            recordFailureFromZod({
              agent: name,
              providerKind: provider.kind ?? 'unknown',
              structuredMode: structuredModeFor(provider.kind, !!outputProfile.toolSchema),
              failureType: 'SCHEMA',
              attempt: 0,
            }, parseErr);
          }
        } else {
          const { keys } = extractedValueSummary(nudgeExtracted);
          llmLog.warn(`Phase 1.5 nudge produced unexpected wrapper (keys=[${keys.join(',')}])`);
        }
      } else {
        const preview = nudgeContent.length > 200 ? `${nudgeContent.slice(0, 200)}...` : nudgeContent;
        llmLog.warn(`Phase 1.5 nudge produced no parseable JSON ── length=${nudgeContent.length} ── preview: "${preview}"`);
      }
    } else {
      llmLog.warn('Phase 1.5 nudge produced no content');
    }
  }

  llmLog.info(`Phase 1 JSON invalid ── entering Phase 2 (schema extraction) ── reason: ${phase1FailReason}`);

  const phase2EmitCount = toolCallRecords.filter((r) => r.name.startsWith('emit_')).length;
  llmLog.warn(`Phase 2 attribution: mode=json emit=${phase2EmitCount} reason=${phase1FailReason}`);

  observer?.onStep?.(name, 2, 'Phase 2: Extracting structured output');

  // Phase 2: only send system + user + synthesized contentText + extraction prompt.
  // Skip all ReAct tool calls/results — contentText already synthesizes the findings
  // from tool calls. This avoids re-sending potentially large tool result payloads
  // (e.g., istqb_guide ~7k tokens, requirement_graph_query ~2k tokens per call).
  // Fallback: if contentText is too short (LLM put analysis in tool results, not content),
  // include the full conversation to preserve context.
  const PHASE2_MIN_CONTENT_LENGTH = 100;
  const useFullConversation = !contentText || contentText.length < PHASE2_MIN_CONTENT_LENGTH;

  let extractionMessages: ChatMessage[];
  if (useFullConversation) {
    llmLog.info(`Phase 2: contentText too short (${contentText.length} chars), using full conversation`);
    extractionMessages = [
      ...conversationMessages,
      { role: 'assistant' as const, content: contentText || '(analysis completed in earlier messages)' },
      { role: 'user' as const, content: buildExtractionPrompt(outputProfile) },
    ];
  } else {
    llmLog.info(`Phase 2: using condensed messages (system + user + contentText only), skipping ${conversationMessages.length - messages.length} ReAct messages`);
    extractionMessages = [
      ...messages,
      { role: 'assistant' as const, content: contentText },
      { role: 'user' as const, content: buildExtractionPrompt(outputProfile) },
    ];
  }

  const MAX_PHASE2_RETRIES = 2;
  let lastError: Error | null = null;
  const baseMessagesLength = extractionMessages.length;
  let lastErrorFeedback: ChatMessage[] | null = null;

  let lastExtractContent = '';

  for (let attempt = 1; attempt <= MAX_PHASE2_RETRIES; attempt++) {
    // Reset to base messages, then re-attach the most recent error feedback so
    // the LLM can self-correct on the next attempt (without unbounded token
    // growth from accumulating feedback across all retries).
    extractionMessages.splice(baseMessagesLength);
    if (lastErrorFeedback) {
      extractionMessages.push(...lastErrorFeedback);
    }

    if ((extra as any)?.signal?.aborted) {
      const reason: any = (extra as any)?.signal?.reason;
      const timedOut = reason != null && String(reason?.name) === 'TimeoutError';
      llmLog.error(`Phase 2 aborted on attempt ${attempt} (${timedOut ? 'timeout' : 'cancelled'})`);
      throw lastError || new Error(
        timedOut
          ? `Agent ${agentName || 'unknown'} timed out after ${(extra as any)?.timeoutMs ?? 'the configured'}ms`
          : 'Aborted',
      );
    }

    llmLog.info(`Phase 2 attempt ${attempt}/${MAX_PHASE2_RETRIES}`);
    observer?.onStep?.(name, 2, `Phase 2: Attempt ${attempt}/${MAX_PHASE2_RETRIES}`);
    const { content: extractContent, finishReason } = await consumeExtractionStream(
      provider,
      extractionMessages,
      buildExtractionChatOptions(outputProfile, extra),
      { onThinking: observer?.onThinking },
      name,
      capturedUsage,
    );

    // 截断独立分支，不进重试：finishReason === 'length' 不是格式错误，
    // 同一 prompt 重试只会再截断、再烧钱。抛给编排层缩小批次（F1 分流）。
    if (finishReason === 'length') {
      llmLog.error(`Phase 2 attempt ${attempt} TRUNCATED by max_tokens (${extractContent.length} chars) ── not retrying, batch must shrink`);
      observer?.onStep?.(name, 3, 'Phase 2: Output truncated — batch shrink required');
      recordFailure({
        agent: name,
        providerKind: provider.kind ?? 'unknown',
        structuredMode: structuredModeFor(provider.kind, !!outputProfile.toolSchema),
        failureType: 'TRUNCATED',
        attempt,
      });
      throw new TruncatedOutputError(name, 'phase2', extractContent.length);
    }

    if (extractContent) {
      // Schema-constrained output should produce valid JSON, but still try parse with fallback.
      // allowTruncatedRepair: false — Phase 2 is the strict path: repairing a
      // truncated payload into a "valid but incomplete" object masks the
      // truncation as missing-field errors and pushes retries to longer outputs.
      const parsed = tryExtractJson(extractContent, { allowTruncatedRepair: false }) ?? (() => {
        try { return JSON.parse(extractContent); } catch { return null; }
      })();

      if (parsed) {
        try {
          const result = outputProfile.parse(outputProfile.normalize(parsed));
          llmLog.success(`Phase 2 extraction successful on attempt ${attempt}`);
          observer?.onStep?.(name, 3, 'Phase 2: Extraction successful');
          return { output: result, usage: capturedUsage, toolCallRecords };
        } catch (schemaErr: any) {
          // Log the FULL validation error (not truncated) as an independent entry
          const fullError = outputProfile.formatValidationError(schemaErr);
          const gapPlan = { mode: 'json' as const, emitCount: 0, layer: 'global' as const, gaps: extractRepairGaps(schemaErr) };
          const errorBlock = [
            `Phase 2 schema validation failed on attempt ${attempt} ── ${formatRepairPlan(gapPlan)}`,
            `  agent: ${name}`,
            `  validation errors:`,
            ...fullError.split('\n').map(l => `    ${l}`),
          ].join('\n');
          llmLog.warn(errorBlock);
          recordFailureFromZod({
            agent: name,
            providerKind: provider.kind ?? 'unknown',
            structuredMode: structuredModeFor(provider.kind, !!outputProfile.toolSchema),
            failureType: 'SCHEMA',
            attempt,
          }, schemaErr);
          // Attach the raw LLM content to the error so scope.ts can persist it
          // to error_raw_response for offline debugging.
          (schemaErr as any).rawResponse = extractContent;
          lastError = schemaErr;

          // 定点修复：只反馈出错字段（path + 原因），让模型在上一份 JSON 上最小改动，
          // 不再重发完整 schema/错误列表 + 整段重生成。
          lastErrorFeedback = buildSchemaRepairFeedback(extractContent, schemaErr);
        }
      } else {
        const preview = extractContent.length > 500 ? `${extractContent.slice(0, 500)}...` : extractContent;
        llmLog.warn(`Phase 2 produced unparseable content on attempt ${attempt} ── length=${extractContent.length} ── content preview: "${preview}"`);
        recordFailure({
          agent: name,
          providerKind: provider.kind ?? 'unknown',
          structuredMode: structuredModeFor(provider.kind, !!outputProfile.toolSchema),
          failureType: 'UNPARSEABLE',
          attempt,
        });
        lastExtractContent = extractContent;
        lastError = new Error('Unparseable content');
        // Persist the raw content for offline debugging.
        (lastError as any).rawResponse = extractContent;

        lastErrorFeedback = [
          { role: 'assistant', content: extractContent },
          { role: 'user', content: 'The output was not valid JSON. Common issues: missing commas between properties, unquoted property names (use "key" not key), trailing commas before ] or }, or unclosed braces/brackets. Output a single valid JSON object matching the schema with no extra text.' },
        ];
      }
    } else {
      llmLog.warn(`Phase 2 produced no content on attempt ${attempt}`);
      recordFailure({
        agent: name,
        providerKind: provider.kind ?? 'unknown',
        structuredMode: structuredModeFor(provider.kind, !!outputProfile.toolSchema),
        failureType: 'NO_CONTENT',
        attempt,
      });
      lastError = new Error('No content produced');

      lastErrorFeedback = [
        { role: 'assistant', content: '(no output)' },
        { role: 'user', content: 'No content was generated. Please ensure you output a single valid JSON object matching the schema.' },
      ];
    }
  }

  if (lastExtractContent) {
    llmLog.error(`Last Phase 2 content (full):\n${lastExtractContent}`);
  }
  llmLog.error(`FAILED to extract structured output after ${MAX_PHASE2_RETRIES} attempts`);
  observer?.onStep?.(name, 3, 'Phase 2: Extraction failed');
  throw lastError || new Error('Failed to extract structured output from LLM response');
}
